-- D.P.Enterprise enquiry storage for Supabase/Postgres
create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  company text,
  email text not null,
  phone text,
  requirement text not null,
  created_at timestamptz not null default now()
);

alter table public.enquiries enable row level security;

-- Public website visitors may submit enquiries, but cannot read them back.
drop policy if exists "allow public enquiry insert" on public.enquiries;
create policy "allow public enquiry insert"
  on public.enquiries
  for insert
  to anon, authenticated
  with check (
    char_length(trim(name)) >= 2 and
    char_length(trim(email)) >= 5 and
    char_length(trim(requirement)) >= 5
  );
